"""Lux — the paintbrush for Claude. Visual output surface for AI agents."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("punt-lux")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

from punt_lux.operations import (
    OpError,
    Pong,
    RenderRequest,
    RenderTableRequest,
    SceneShown,
)
from punt_lux.paths import DisplayPaths
from punt_lux.protocol import (
    AckMessage,
    ButtonElement,
    CheckboxElement,
    CollapsingHeaderElement,
    ColorPickerElement,
    ComboElement,
    DrawElement,
    FrameReader,
    GroupElement,
    ImageElement,
    InputTextElement,
    MarkdownElement,
    MenuMessage,
    PingMessage,
    PlotElement,
    PongMessage,
    ProgressElement,
    RadioElement,
    ReadyMessage,
    RegisterMenuMessage,
    RemoteEventHandlerInvocation,
    SceneMessage,
    SelectableElement,
    SeparatorElement,
    SliderElement,
    SpinnerElement,
    TabBarElement,
    TableElement,
    TextElement,
    TreeElement,
    WindowElement,
    decode_frame,
    encode_frame,
    encode_message,
    message_from_dict,
    message_to_dict,
    recv_message,
    send_message,
)
from punt_lux.rest_client import LuxRestClient
from punt_lux.rest_transport import HubUnavailableError

__all__ = [
    "AckMessage",
    "ButtonElement",
    "CheckboxElement",
    "CollapsingHeaderElement",
    "ColorPickerElement",
    "ComboElement",
    "DisplayPaths",
    "DrawElement",
    "FrameReader",
    "GroupElement",
    "HubUnavailableError",
    "ImageElement",
    "InputTextElement",
    "LuxRestClient",
    "MarkdownElement",
    "MenuMessage",
    "OpError",
    "PingMessage",
    "PlotElement",
    "Pong",
    "PongMessage",
    "ProgressElement",
    "RadioElement",
    "ReadyMessage",
    "RegisterMenuMessage",
    "RemoteEventHandlerInvocation",
    "RenderRequest",
    "RenderTableRequest",
    "SceneMessage",
    "SceneShown",
    "SelectableElement",
    "SeparatorElement",
    "SliderElement",
    "SpinnerElement",
    "TabBarElement",
    "TableElement",
    "TextElement",
    "TreeElement",
    "WindowElement",
    "decode_frame",
    "encode_frame",
    "encode_message",
    "message_from_dict",
    "message_to_dict",
    "recv_message",
    "send_message",
]
