name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: DavidAnson/markdownlint-cli2-action@1f341f4c23330757d549a0c1fcb3812ece7a7826 # v22
        with:
          globs: |
            **/*.md
            #node_modules
